class Moves:
	DO_NOTHING = -1
	MOVE_UP = 1
	MOVE_LEFT = 2
	MOVE_RIGHT = 3
	MOVE_DOWN = 4
	PLACE_BOMB = 5
	TRIGGER_BOMB = 6

	VALID_MOVES = [ DO_NOTHING, MOVE_UP, MOVE_LEFT, MOVE_RIGHT, MOVE_DOWN, PLACE_BOMB, TRIGGER_BOMB ]
